/**
 * Stored notation format — the ONLY thing allowed to interpret Question.prompt,
 * QuestionOption.text, or QuestionOption.misconception.
 *
 * THE FORMAT
 *   Plain UTF-8 text. Math goes inside single dollar signs, written in the
 *   KaTeX subset allowed below:
 *
 *       Evaluate $3x^2 - 2$ at $x = -2$
 *       For $x \ne 3$, simplify: $\frac{x^2 - 9}{x - 3}$
 *
 *   A literal dollar sign in text is written \$. A newline is a line break.
 *   That is the entire format. It is NOT HTML and NOT Markdown.
 *
 * WHY, AND THE RULE THAT MAKES IT SAFE
 *   The prototype built stems as HTML strings and injected them with
 *   innerHTML. That is fine for a file you wrote yourself and unacceptable the
 *   moment a teacher submission form writes to the same column.
 *
 *   The rule: teacher input never reaches a render path as markup.
 *     - Text segments render as React text children. React escapes them, so a
 *       teacher who types <script> gets the literal characters <script> on
 *       screen. There is no HTML path for them to reach.
 *     - Math segments are not teacher HTML either — they are LaTeX source,
 *       validated on write (below) and compiled by KaTeX with trust:false,
 *       which refuses \href, \url and \includegraphics. The only HTML that ever
 *       reaches dangerouslySetInnerHTML is machine-generated by KaTeX from
 *       source that already passed this validator, one math span at a time.
 *
 *   Validation runs at every write: the seed, and any future admin/teacher
 *   form. Invalid stems never reach the database, so the render path can trust
 *   the column.
 *
 * WHY KATEX AND NOT A HAND-ROLLED MARKUP
 *   A restricted markup rendered straight to React elements touches no HTML at
 *   all, which is one notch safer in principle. It also means writing and
 *   maintaining a math parser. Superscripts and inequalities are easy;
 *   fractions, roots, limits and piecewise braces are where a homegrown parser
 *   starts growing escaping bugs of its own — and Calc BC II and Physics C are
 *   already on the roadmap. KaTeX is the better-tested parser, the residual
 *   risk is confined to a machine-generated span, and the allowlist below keeps
 *   the reachable surface small.
 */

import katex from "katex";

/** Frozen so the seed, the validator and the renderer cannot drift apart. */
export const KATEX_OPTIONS = Object.freeze({
  displayMode: false,
  throwOnError: true,
  /** Never true. trust:true is what re-enables \href and \includegraphics. */
  trust: false,
  strict: "warn" as const,
  output: "htmlAndMathml" as const,
  maxSize: 20,
  maxExpand: 200,
});

/**
 * Every command an author may use. Deliberately short: add to it when a teacher
 * asks for something, not preemptively. Anything not listed fails validation
 * with a message naming the command.
 */
const ALLOWED_COMMANDS = new Set([
  // structure
  "frac", "dfrac", "tfrac", "sqrt", "left", "right", "begin", "end",
  "text", "mathrm", "quad", "qquad", "displaystyle",
  // relations and operators
  "le", "leq", "ge", "geq", "ne", "neq", "lt", "gt", "approx", "equiv",
  "cdot", "times", "div", "pm", "mp", "to", "mapsto", "implies",
  // symbols
  "infty", "pi", "theta", "alpha", "beta", "lambda", "mu", "Delta", "circ",
  "ldots", "cdots", "dots",
  // functions students will meet
  "log", "ln", "sin", "cos", "tan", "lim", "limits", "sum", "int",
  // marks
  "overline", "vec", "bar", "hat",
]);

/** Environments allowed inside \begin{...} ... \end{...}. */
const ALLOWED_ENVIRONMENTS = new Set(["cases", "array", "aligned", "matrix", "pmatrix", "bmatrix"]);

/**
 * Redundant with the allowlist, kept explicit so the intent survives someone
 * widening ALLOWED_COMMANDS in a hurry. These are the commands that turn KaTeX
 * output into an injection vector or a denial of service.
 */
const NEVER_ALLOWED = [
  "href", "url", "includegraphics", "htmlData", "htmlClass", "htmlId", "htmlStyle",
  "def", "gdef", "edef", "xdef", "let", "newcommand", "renewcommand", "expandafter",
];

const MAX_STEM_LENGTH = 2000;
const MAX_MATH_SEGMENT_LENGTH = 500;

export type StemSegment =
  | { kind: "text"; value: string }
  | { kind: "math"; value: string };

export class NotationError extends Error {
  constructor(label: string, detail: string) {
    super(`${label}: ${detail}`);
    this.name = "NotationError";
  }
}

/**
 * Split a stem into text and math segments. Pure string work — no HTML, no DOM.
 * The renderer maps text segments to React text children and math segments to
 * KaTeX.
 */
export function parseStem(src: string): StemSegment[] {
  const segments: StemSegment[] = [];
  let buffer = "";
  let inMath = false;

  for (let i = 0; i < src.length; i++) {
    const char = src[i];

    if (char === "\\" && src[i + 1] === "$" && !inMath) {
      buffer += "$";
      i++;
      continue;
    }

    if (char === "$") {
      if (buffer.length > 0 || inMath) {
        segments.push({ kind: inMath ? "math" : "text", value: buffer });
      }
      buffer = "";
      inMath = !inMath;
      continue;
    }

    buffer += char;
  }

  if (inMath) {
    throw new NotationError("stem", "unbalanced $ — every math segment needs a closing $");
  }
  if (buffer.length > 0) {
    segments.push({ kind: "text", value: buffer });
  }

  return segments;
}

/**
 * Throw unless `src` is a valid stem. Call this on every write path. `label`
 * identifies the field in the error message so a failing seed says which
 * question is wrong.
 */
export function assertValidStem(src: string, label: string): void {
  if (src.trim().length === 0) {
    throw new NotationError(label, "empty");
  }
  if (src.length > MAX_STEM_LENGTH) {
    throw new NotationError(label, `longer than ${MAX_STEM_LENGTH} characters`);
  }

  let segments: StemSegment[];
  try {
    segments = parseStem(src);
  } catch (error) {
    throw new NotationError(label, (error as Error).message);
  }

  for (const segment of segments) {
    if (segment.kind === "text") {
      const offender = /[<>]/.exec(segment.value);
      if (offender) {
        throw new NotationError(
          label,
          `"${offender[0]}" outside math. Write it as math instead, e.g. $x < 1$`,
        );
      }
      continue;
    }

    if (segment.value.trim().length === 0) {
      throw new NotationError(label, "empty math segment ($$)");
    }
    if (segment.value.length > MAX_MATH_SEGMENT_LENGTH) {
      throw new NotationError(label, `math segment longer than ${MAX_MATH_SEGMENT_LENGTH} characters`);
    }

    for (const command of NEVER_ALLOWED) {
      if (segment.value.includes(`\\${command}`)) {
        throw new NotationError(label, `\\${command} is never allowed`);
      }
    }

    for (const match of segment.value.matchAll(/\\([a-zA-Z]+)/g)) {
      const command = match[1];
      if (!ALLOWED_COMMANDS.has(command)) {
        throw new NotationError(
          label,
          `\\${command} is not in the allowlist (lib/notation.ts). Add it deliberately if a teacher needs it.`,
        );
      }
    }

    for (const match of segment.value.matchAll(/\\begin\{([a-zA-Z*]+)\}/g)) {
      const environment = match[1];
      if (!ALLOWED_ENVIRONMENTS.has(environment)) {
        throw new NotationError(label, `environment "${environment}" is not in the allowlist`);
      }
    }

    try {
      katex.renderToString(segment.value, KATEX_OPTIONS);
    } catch (error) {
      throw new NotationError(label, `KaTeX rejected "${segment.value}" — ${(error as Error).message}`);
    }
  }
}
